spring:
  application:
    name: micro-cart
  redis:
    host: localhost
    port: 6379
    #password:

server:
  port: 8033
  context-path: /cart
  tomcat:
    uri-encoding: UTF-8

logging:
  config: classpath:log4j2.xml

eureka:
  instance:
    hostname: micro-cart
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka1:8001/eureka,http://eureka2:8002/eureka,http://eureka3:8003/eureka
