spring:
  application:
    name: micro-shoppingcart
  redis:
    host: localhost
    port: 6379
    #password:

server:
  port: 8023
  context-path: /shoppingcart
  tomcat:
    uri-encoding: UTF-8

logging:
  config: classpath:log4j2.xml

eureka:
  instance:
    hostname: micro-shoppingcart
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka1:8001/eureka,http://eureka2:8001/eureka,http://eureka3:8001/eureka
