spring:
  application:
    name: micro-eureka-server

server:
  port: 8001

---
spring:
  profiles: eureka1

eureka:
  instance:
    hostname: eureka1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka2:8001/eureka/,http://eureka3:8001/eureka

---
spring:
  profiles: eureka2

eureka:
  instance:
    hostname: eureka2
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka1:8001/eureka/,http://eureka3:8001/eureka

---
spring:
  profiles: eureka3

eureka:
  instance:
    hostname: eureka3
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka1:8001/eureka/,http://eureka2:8001/eureka
