spring:
  application:
    name: micro-eureka-server

---
spring:
  profiles: eureka1

server:
  port: 8001

eureka:
  instance:
    hostname: eureka1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka2:8002/eureka/,http://eureka3:8003/eureka

---
spring:
  profiles: eureka2

server:
  port: 8002

eureka:
  instance:
    hostname: eureka2
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka1:8001/eureka/,http://eureka3:8003/eureka

---
spring:
  profiles: eureka3

server:
  port: 8003

eureka:
  instance:
    hostname: eureka3
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka1:8001/eureka/,http://eureka2:8002/eureka
