spring:
  application:
    name: micro-account
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/account
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20

server:
  port: 8031
  context-path: /account

logging:
  config: classpath:log4j2.xml

eureka:
  instance:
    hostname: micro-account
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka1:8001/eureka,http://eureka2:8002/eureka,http://eureka3:8003/eureka
