spring:
  application:
    name: micro-view
  resources:
    static-locations: classpath:/static/

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

logging:
  config: classpath:log4j2.xml

eureka:
  instance:
    hostname: micro-view
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka1:8001/eureka,http://eureka2:8002/eureka,http://eureka3:8003/eureka
