spring:
  application:
    name: micro-view
  thymeleaf:
    cache: false

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
#    accesslog:
#      enabled: true
#    basedir: target/tomcat

eureka:
  instance:
    hostname: micro-view
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka1:8001/eureka,http://eureka2:8001/eureka,http://eureka3:8001/eureka
